version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx/
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    networks:
      - laravel
    volumes:
      - ./src/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dockerfiles/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel
networks:
  laravel:
    driver: bridge

  

  